# Generated by Django 3.2 on 2021-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="autoAccount",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="countryCode",
            field=models.CharField(
                blank=True, default="55", max_length=155, verbose_name="Codigo do pais"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="localAreaCode",
            field=models.CharField(
                blank=True, default="", max_length=155, verbose_name="DDD"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="news_letter",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notifications",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phoneNumber",
            field=models.CharField(
                blank=True, default="", max_length=155, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.FileField(default="core/smalllogo.png", upload_to="avatars/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="sms",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="testUser",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="validEmail",
            field=models.BooleanField(default=False),
        ),
    ]
