# Generated by Django 3.2 on 2021-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenreModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512, verbose_name="Titulo")),
                ("slug", models.SlugField()),
            ],
            options={
                "verbose_name": "Genero",
                "verbose_name_plural": "Generos",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MovieModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                (
                    "stackOrder",
                    models.FloatField(default=100, verbose_name="Ordem de exibição"),
                ),
                ("title", models.CharField(max_length=512, verbose_name="Titulo")),
                ("description", models.TextField(verbose_name="Descrição")),
                ("excerpt", models.TextField(verbose_name="Resumo")),
            ],
            options={
                "verbose_name": "Filme",
                "verbose_name_plural": "Filmes",
                "ordering": ["stackOrder"],
                "abstract": False,
            },
        ),
    ]
