# Generated by Django 3.2 on 2021-05-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StripeSettingsModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        max_length=144, verbose_name="Nome da configuração"
                    ),
                ),
                (
                    "publicKey",
                    models.CharField(
                        default="", max_length=512, verbose_name="Stripe Public Key"
                    ),
                ),
                (
                    "privateKey",
                    models.CharField(
                        default="", max_length=512, verbose_name="Stripe Private Key"
                    ),
                ),
                ("isDefaultSettings", models.BooleanField(default=False, unique=True)),
            ],
            options={
                "verbose_name": "Conta Stripe",
                "verbose_name_plural": "Contas Stripe",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
    ]
