version: "3.9"


services:

  cache:
    restart: always
    image: memcached
    env_file:
      - .env-memcache.yaml
      - .env-common.yaml

    expose:
      - 11211
    entrypoint:
      - memcached
      - -m 64


  django_project:
    restart: always
    volumes:
      - "./django_project/:/home/django_project/"

    build:
      context: ./django_docker
      dockerfile: Dockerfile
    command: bash -c /home/django_project/entrypoint.sh
    ports:
      - 8010:8001

    env_file:
      - .env-db.yaml
      - .env-api.yaml
      - .env-redis.yaml
      - .env-memcache.yaml
      - .env-common.yaml

    depends_on:
      - cache
      - redis

  nginx_static_server:
    restart: always
    build:
      context: ./nginx_server
      dockerfile: Dockerfile

    env_file:
      - .env-nginx.yaml
      - .env-common.yaml
      - .env-api.yaml

    volumes:
      - "./django_project/:/home/django_project/"
    # Onde está o acesso ao static e ao media
    ports:
      - 9010:80

    depends_on:
      - django_project
      - cache
      - redis

volumes:
  static_volume:
  media_volume:
  datastore_volume:
