"""
Django settings for ecoway project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

AUTH_USER_MODEL = "accounts.User"

redis_host = os.environ.get("REDIS_HOST", "localhost")

CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(redis_host, 6379)],
        },
    },
}

SITE_ID = 1

SECRET_KEY = os.environ.get("SECRET_KEY", default="fake-key")

DEBUG = int(os.environ.get("DEBUG", default=0))
LOCAL = int(os.environ.get("LOCAL", default=0))

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]

API_VERSION = 1

ASGI_APPLICATION = "uood.routing.application"

REST_FRAMEWORK = {
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework_xml.parsers.XMLParser",
    ],
    # "EXCEPTION_HANDLER": "server.exception_handler.custom_exception_handler",
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "1000/day", "user": "10000/day"},
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "project.pagination.FlutterPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

ADMIN_TOOLS_INDEX_DASHBOARD = "project.dashboard.main.MainDashboard"
ADMIN_TOOLS_APP_INDEX_DASHBOARD = "project.dashboard.main.MainAppIndexDashboard"
ADMIN_TOOLS_MENU = "project.dashboard.menu.MainMenu"
ADMIN_TOOLS_THEMING_CSS = "frontend/css/dashboard.css"

INSTALLED_APPS = [
    "project.apps.ProjectConfig",
    "accounts.apps.AccountsConfig",
    "admin_tools",
    "admin_tools.theming",
    "admin_tools.menu",
    "admin_tools.dashboard",
    "channels",
    "leaflet",
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.sites",
    "django.contrib.flatpages",
    "django.contrib.gis",
    "django.contrib.humanize",
    "corsheaders",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:9000",
    "http://localhost",
    "http://127.0.0.1:8000",
]


FILER_CANONICAL_URL = "sharing/"
THUMBNAIL_HIGH_RESOLUTION = True

# THUMBNAIL_PROCESSORS = (
#     'easy_thumbnails.processors.colorspace',
#     'easy_thumbnails.processors.autocrop',
#     # 'easy_thumbnails.processors.scale_and_crop',
#     'filer.thumbnail_processors.scale_and_crop_with_subject_location',
#     'project.thumbnail_processors.circle_processor',
#     'easy_thumbnails.processors.filters'
#     )

THUMBNAIL_ALIASES = {
    "": {"avatar": {"size": (128, 128), "crop": True}},
}

MIDDLEWARE = []

if not DEBUG:
    MIDDLEWARE = ["django.middleware.cache.UpdateCacheMiddleware"]
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True

MIDDLEWARE += [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.flatpages.middleware.FlatpageFallbackMiddleware",
]

if not DEBUG:
    MIDDLEWARE += ["django.middleware.cache.FetchFromCacheMiddleware"]


ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
                "admin_tools.template_loaders.Loader",
            ],
        },
    },
    # {
    #     "NAME":"systemwide",
    #     "BACKEND": "django.template.backends.django.DjangoTemplates",
    #     "DIRS": [
    #         os.path.join(BASE_DIR, "templates"),
    #     ],
    #     "APP_DIRS": False,
    #     "OPTIONS": {
    #         "context_processors": [
    #             "django.template.context_processors.debug",
    #             "django.template.context_processors.request",
    #             "django.contrib.auth.context_processors.auth",
    #             "django.contrib.messages.context_processors.messages",
    #             "django.template.context_processors.media",
    #         ],
    #         "loaders": [
    #             "django.template.loaders.filesystem.Loader",
    #             "django.template.loaders.app_directories.Loader",
    #             "admin_tools.template_loaders.Loader",
    #         ],
    #     },
    # },
]


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.memcached.MemcachedCache",
        "LOCATION": "127.0.0.1:11211",
        "TIMEOUT": 120,
        "OPTIONS": {"server_max_value_length": 1024 * 1024 * 100},
    }
}

WSGI_APPLICATION = "project.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": os.environ.get(
            "SQL_ENGINE", "django.contrib.gis.db.backends.postgis"
        ),
        "NAME": os.environ.get("SQL_DATABASE", "django_db"),
        "USER": os.environ.get("SQL_USER", "django_user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "django_password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


LEAFLET_CONFIG = {
    "DEFAULT_CENTER": (-49, -29),
    "DEFAULT_ZOOM": 4,
    "MAX_ZOOM": 20,
    "MIN_ZOOM": 3,
    "SCALE": "both",
    "ATTRIBUTION_PREFIX": "Inspired by Life in GIS (Lauro Cesar)",
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static/frontend/")]

LANGUAGE_CODE = "pt-br"

LANGUAGES = [("pt-br", "Português")]

TIME_ZONE = "UTC"

USE_I18N = True
USE_THOUSAND_SEPARATOR = True
USE_L10N = True

USE_TZ = True

# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]  # add STATIC_ROOT to DIRS

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
STATIC_URL = "/static/"
MEDIA_URL = "/media/"
