# Generated by Django 3.2 on 2021-05-04 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLanguageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Última modificacao')),
                ('isActive', models.BooleanField(default=True)),
                ('isPublic', models.BooleanField(default=False)),
                ('language_name', models.CharField(max_length=255, verbose_name='Nome da linguagem')),
                ('language_code', models.CharField(max_length=8, verbose_name='Código da linguagem')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='appsettingmodel',
            options={'ordering': ['created'], 'verbose_name': 'Configuração do aplicativo', 'verbose_name_plural': 'Configurações do aplicativo'},
        ),
        migrations.RemoveField(
            model_name='appsettingmodel',
            name='label',
        ),
        migrations.AddField(
            model_name='appsettingmodel',
            name='release_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Nome do aplicativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettingmodel',
            name='languages',
            field=models.ManyToManyField(to='app_settings.AppLanguageModel'),
        ),
    ]
