# Generated by Django 3.2 on 2021-05-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_auto_20210504_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='applanguagemodel',
            name='language_icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/languages/'),
        ),
    ]
