# Generated by Django 3.2 on 2021-05-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_applanguagemodel_language_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applanguagemodel',
            options={'ordering': ['created'], 'verbose_name': 'Tradução', 'verbose_name_plural': 'Traduções'},
        ),
    ]
