# Generated by Django 3.2 on 2021-05-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0006_alter_applanguagemodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applanguagebaseentrymodel",
            options={
                "ordering": ["created"],
                "verbose_name": "String traduzivel",
                "verbose_name_plural": "Strings traduziveis",
            },
        ),
        migrations.AlterField(
            model_name="applanguagebaseentrymodel",
            name="entry_key",
            field=models.CharField(
                blank=True,
                help_text="Deixe em branco para auto criar",
                max_length=255,
                verbose_name="ID único",
            ),
        ),
        migrations.AlterField(
            model_name="applanguagebaseentrymodel",
            name="entry_original_value",
            field=models.TextField(
                help_text="String original enviada automaticamente pelo applicativo",
                verbose_name="String original",
            ),
        ),
    ]
