# Generated by Django 3.2 on 2021-05-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0009_remove_applanguagebaseentrymodel_entry_screenshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppLanguageEntryKeyModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                (
                    "entry_original_value",
                    models.TextField(
                        help_text="String original enviada automaticamente pelo applicativo",
                        verbose_name="String original",
                    ),
                ),
                (
                    "entry_description",
                    models.TextField(
                        help_text="Explicação de onde essa string aparece",
                        verbose_name="Onde encontro isso no app?",
                    ),
                ),
                (
                    "entry_key",
                    models.CharField(
                        blank=True,
                        help_text="Deixe em branco para auto criar",
                        max_length=255,
                        verbose_name="ID único",
                    ),
                ),
                (
                    "entry_original_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_keys",
                        to="app_settings.applanguagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "String traduzivel",
                "verbose_name_plural": "Strings traduziveis",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AppLanguageTranslationEntryModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now=True, verbose_name="Data de criação"),
                ),
                (
                    "lastModified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última modificacao"
                    ),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("isPublic", models.BooleanField(default=False)),
                (
                    "translation_entry_value",
                    models.TextField(
                        help_text="String original enviada automaticamente pelo applicativo",
                        verbose_name="Tradução",
                    ),
                ),
                (
                    "entry_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations_entries",
                        to="app_settings.applanguageentrykeymodel",
                    ),
                ),
                (
                    "entry_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_values",
                        to="app_settings.applanguagemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "String traduzida",
                "verbose_name_plural": "Strings traduzidas",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="AppLanguageBaseEntryModel",
        ),
    ]
