# Generated by Django 3.2 on 2021-05-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_settings", "0011_alter_applanguageentrykeymodel_entry_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appsettingmodel",
            old_name="isPrimary",
            new_name="isDefaultSettings",
        ),
    ]
