# Generated by Django 3.2.1 on 2021-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_subscriptions', '0002_alter_appsubscriptionplanmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsubscriptionplanmodel',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do plano'),
        ),
    ]
